#!/bin/bash

__dirname="$(dirname "$(realpath "${BASH_SOURCE[0]:-$0}")")"

isWSL() { [[ -n $IS_WSL || -n $WSL_DISTRO_NAME ]] && (( $1 + WSL2_GUI_APPS_ENABLED != 2 )) ; }

index_html="${__dirname}/HoYo.Gacha/index.html"
tauri_conf="${__dirname}/HoYo.Gacha/src-tauri/tauri.conf.json"
tauri_shell_config='"shell": { "all": true, "execute": true, "scope": [{ "name": "trans", "cmd": "trans", "args": true }] }'
darkreader_cdn='<script defer src="https://cdn.jsdelivr.net/npm/darkreader@latest"></script>'
[[ -f $index_html ]] || git submodule update --init --remote --force || exit 1

cp -rf "${__dirname}/patched/src" "${__dirname}/HoYo.Gacha"
sed -i "/locale/d" "${__dirname}/HoYo.Gacha/src/utilities/dayjs.ts"
sed -i "s/\"shell\": { \"all\": true }/${tauri_shell_config}/" "$tauri_conf"
sed -i "6i \ \ \ \ ${darkreader_cdn}" "$index_html"
sed -i 's/lang="zh"/lang="en-US"/' "$index_html"
sed -i "s/zh-CN/en-US/" "$tauri_conf"

cd "${__dirname}/HoYo.Gacha" || exit 1
{ tail -F /dev/null --pid=$$ && nohup git restore :/ & } &> /dev/null
pnpm=pnpm && isWSL 1 && pnpm+=.exe ; exec $pnpm "$@"
